#pragma once
#ifndef DECLARE_NAMESPACE
#define DECLARE_NAMESPACE
#define END_SPACE }
#endif // ! DECLARE_NAMESPACE
#ifndef DECLARE_NAMESPACE_SHAREFORM
#define DECLARE_NAMESPACE_SHAREFORM
#define SPACE_SHAREFORM shareform
#define USING_SHAREFORM using namespace SF_SHAREFORM
#define BEGINE_SPACE_SHAREFORM namespace SF_SHAREFORM {
#endif // !DECLARE_NAMESPACE_SHAREFORM
#ifndef DECLARE_NAMESPACE_SF_OBJECT
#define DECLARE_NAMESPACE_SF_OBJECT
#define SPACE_SF_OBJECT shareform::object
#define USING_SF_OBJECT using namespace SPACE_SF_OBJECT
#define BEGINE_SPACE_SF_OBJECT namespace SPACE_SF_OBJECT {
#endif // !DECLARE_NAMESPACE_OBJECT
#ifndef DECLARE_NAMESPACE_SF_SINGLETON
#define DECLARE_NAMESPACE_SF_SINGLETON
#define SPACE_SF_SINGLETON shareform::singleton
#define USING_SF_SINGLETON using namespace SPACE_SF_SINGLETON 
#define BEGINE_SPACE_SF_SINGLETON namespace SPACE_SF_SINGLETON {
#endif // !DECLARE_NAMESPACE_SINGLETON
#ifndef DECLARE_NAMESPACE_SF_SEQUENCE
#define DECLARE_NAMESPACE_SF_SEQUENCE
#define SPACE_SF_SEQUENCE shareform::sequence
#define USING_SF_SEQUENCE using namespace SPACE_SF_SEQUENCE 
#define BEGINE_SPACE_SF_SEQUENCE namespace SPACE_SF_SEQUENCE {
#endif // !DECLARE_NAMESPACE_SEQUENCE
#ifndef DECLATE_NAMESPACE_SF_COMMAND
#define DECLATE_NAMESPACE_SF_COMMAND
#define SPACE_SF_COMMAND shareform::command
#define USING_SF_COMMAND using namespace SPACE_SF_COMMAND
#define BEGINE_SPACE_SF_COMMAND namespace SPACE_SF_COMMAND {
#endif // !DECLATE_NAMESPACE_SF_COMMAND


